name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This dedicated tool automatically handles all SDK bugs, Java, and missing AIDL files!
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK File
        uses: actions/upload-artifact@v4
        with:
          name: DocumentChecker-App
          path: bin/*.apk
