name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libltdl-dev libffi-dev libssl-dev python3-dev zip unzip openjdk-17-jdk zlib1g-dev

      - name: Install Buildozer
        run: pip3 install buildozer cython==0.29.33

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK File
        uses: actions/upload-artifact@v4
        with:
          name: DocumentChecker-App
          path: bin/*.apk
